### ISSUE TITLE
Overwrites Save Data Without Warning

### ISSUE THREAD

**Issue by heare2code** [Ninja-Cookie/BRCTools#1]
Using the built in saves overwrites the save you are loaded in without any prior notice. Luckily I backed up my save after beating BRC for the first time and before using any mods so it's not as big as a deal for me, but for people who don't back up their saves may get really mad knowing their save is now overwritten with another save with no way of getting the save used before back.
My suggestion is to add a warning below the Selected Save header or when your mouse is over saying that this will overwrite your current save slot and to suggest or automatically turn off auto saving when loading into these saves.

**Comment by Ninja-Cookie** [comment]
This is primarily used for speedrunning so clearing savedata wasn't something I considered and didn't expect it to reach many people outside of the speedrunning circle, though you make a good point that it isn't clear. I don't necessarily want to add a warning if possible, I might just look into maybe backing up the save for you automatically when you load one, not too sure how possible it is. On the idea of not saving the new save that was loaded, in order to load that data into memory, it requires I pass the game data to the game to save it, then reload the current state so it loads in the new memory I just gave it, making that not too possible, however I maybe could make it so it stores the current binary info, overrights and saves it, then loads your original data and saves that. I will think on it.

**Comment by Ninja-Cookie** [comment]
I went the simple route and re-labelled these buttons to be more clear on what they exactly do.

![image](https://github.com/Ninja-Cookie/BRCTools/assets/62808028/9a6b4aed-1c37-4693-b35d-0c54c5307bd0)

I'll close the issue once this is implemented in the next version but will leave it open currently in-case anything wants to be commented on about it.
